name: Mise à jour du Heatmap

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures (format UTC)
  workflow_dispatch:  # Permet un déclenchement manuel

jobs:
  generate-heatmap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib requests

      - name: Exécuter le script
        run: python heatmap_generator.py

      - name: Téléverser vers ThingSpeak
        env:
          API_KEY: ${{ secrets.THINGSPEAK_API_KEY }}
        run: |
          curl -X POST \
            -H "Content-Type: multipart/form-data" \
            -F "image=@heatmap.png" \
            "https://api.thingspeak.com/channels/2907557/images.json?api_key=$API_KEY"
