name: Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Version majeure mise à jour
        with:
          name: site
          path: .
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
